### ISSUE TITLE
display nothing

### ISSUE THREAD

**Issue by rudy1976s** [jtraulle/CakeCharts#1]
I have followed your docs and properly configured.
The div which should contain the chart is created 

`<div id="chart_595375ed3575d" class="js-plotly-plot"></div>`

but I have the following error in console

`plotly-latest.min.js:58 Uncaught TypeError: Cannot use 'in' operator to search for 'line' in null
    at a (plotly-latest.min.js:58)
    at Object.r.cleanData (plotly-latest.min.js:59)
    at Object.y.plot (plotly-latest.min.js:59)
    at Object.y.newPlot (plotly-latest.min.js:59)
    at admin:673`

and no chart displayed

**Comment by jtraulle** [comment]
Hey @rudy1976s ,

Sorry to hear that.

Can you copy/paste generated Javascript before closing ```</body>``` tag by displaying the source of your page.
It should start by :

```html
<script type="text/javascript">
    var data = 
```

Also copy PHP call to helper from your view please 😉

**Comment by rudy1976s** [comment]
Hi Jean

Thank you for your reply.

Here it is the code but it is before closing BODY tag not HEAD.



    var data = [{"x":["Apples","Tomatoes","Bananas","Cherries"],"y":[38,22,55,96],"type":"bar","name":null,"marker":null}];
    var layout = {};
    var configuration = {}
    Plotly.newPlot('chart_59537a08e10b7', data, layout, configuration);


Here it is helper code 

<?= $this->DrawChart->simpleBarChart(
    ['Apples', 'Tomatoes', 'Bananas', 'Cherries'],
    [38, 22, 55, 96]); ?>

Hope this helps


Rudy

**Comment by jtraulle** [comment]
Thanks for the details @rudy1976s :)

Could you update to v1.1.1 ? Should be fixed now.
My mistake 😉

**Comment by rudy1976s** [comment]
I will do update this evening and let you know.
Thank you again

**Comment by rudy1976s** [comment]
I am happy to tell you that now it works!!!!!
I like your plugin: is there a way to extend functionalities to other charts libraries ?
Thank you again

Rudy

**Comment by jtraulle** [comment]
Thanks for your feedback 👍 

Right now, I have based my implementation on Plot.ly but it would be great to support other charts libraries.

We just must be cautious about licensing.

I have chosen Plot.ly because it is MIT licensed but I think [ChartJS](http://www.chartjs.org/), also MIT licensed would be a great addition, especially because it can handle polar and radar charts which Plot.ly can not, at this time 😉 

Nothing is impossible with code and extend functionalities to other charts libraries is definitely possible. 

If you're interested about contributing, feel free to open another issue to deeper discuss this and a pull request if needed 😃

**Comment by rudy1976s** [comment]
It would be great to add support for Chart.JS library too.

Yesterday I have tried to work a bit on it:  did you provide config to manage the tools bar provided by the flow  chart plugin ? It would be good to be able to enable/disable features by configurations.
I will continue to test it and see if some idea will comes out!


Rudy

**Comment by jtraulle** [comment]
If you are talking about the toolbar that appear on hover, yes, you can change that by passing a configuration array (see $configuration key in phpDoc and Plot.ly corresponding page https://plot.ly/javascript/configuration-options/)
